// <auto-generated />
namespace T2009M_NguyenThiLinh_ExamWAD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Exam : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Exam));
        
        string IMigrationMetadata.Id
        {
            get { return "202112280427549_Exam"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
